Models/BillingMethod.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AbsolCase.Models
{
    public class BillingMethod
    {
        public int Id { get; set; }
        [RegularExpression(@"^[^\s]+(\s+[^\s]+)*$", ErrorMessage = "Please avoid white spaces.")]
        [Required(ErrorMessage= "Billing Name is Required")]
        public string Name { get; set; }
        public int? FirmId { get; set; }
        public string UserId { get; set; }
    }
}

Areas/Public/Controllers/SubscriptionController.cs
using AbsolCase.Configuration;
using AbsolCase.Configurations;
using AbsolCase.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.Identity.Client;
using Microsoft.Win32;
using Newtonsoft.Json;
using PayPal;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using static AbsolCase.Configuration.RequestSender;

namespace AbsolCase.Areas.Public.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly INotyfService _notyf;
        private readonly MyConfiguration _myConfiguration;
        public SubscriptionController(INotyfService notyf, IOptions<MyConfiguration> myConfiguration)
        {
            _notyf = notyf;
            _myConfiguration = myConfiguration.Value;
        }

        public IActionResult Index()
        {
            SResponse resp = Fetch.GotoService("api", "PricePlan/GetPackages", "GET");
            if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
            {
                List<PackageService> package = JsonConvert.DeserializeObject<List<PackageService>>(resp.Resp);
                return View(package);
            }
            return View();
        }
        public IActionResult ReSubscribe()
        {
            SResponse resp = Fetch.GotoService("api", "PricePlan/GetPackages", "GET");
            if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
            {
                List<PackageService> packages = JsonConvert.DeserializeObject<List<PackageService>>(resp.Resp);
                string userdto = HttpContext.Session.GetString("userData");
                if (packages != null && packages.Count > 0 && !string.IsNullOrEmpty(userdto))
                {
                    UserDto userDto = JsonConvert.DeserializeObject<UserDto>(userdto);
                    if (userDto.PricePlanIds != null && userDto.PricePlanIds.Count > 0)
                        packages = packages.Where(x => !userDto.PricePlanIds.Contains(x.pricePlan.PlanID)).ToList();
                }
                return View(packages);
            }
            return View();
        }
        public IActionResult BillingMethod(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult BillingMethod(SignupDto signupDto)
        {
            try
            {
                var body = JsonConvert.SerializeObject(signupDto);
                SResponse resp = Fetch.GotoService("api", "UserManagement/register", "POST", body);
                if (resp.Status)
                {
                    return RedirectToAction("Index", "AttorneyDashboard", new { Area = "Attorney" });
                }
                else
                {
                    TempData["response"] = resp.Resp + " " + "Unable To register user";
                    return RedirectToAction("BillingMethod");
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public IActionResult PaymentWithPaypal()
        {
            try
            {
                //getting the apiContext
                APIContext apiContext = PaypalConfiguration.GetAPIContext();
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = HttpContext.Request.Query["PayerID"];

                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class

                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = $"{Request.Scheme}://{Request.Host.Value}" +
                                "/cms/Public/Subscription/PaymentWithPaypal?";

                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution

                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment
                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = CreatePayment(apiContext, baseURI + "guid=" + guid);

                    //get links returned from paypal in response to Create function call

                    var links = createdPayment.links.GetEnumerator();

                    string paypalRedirectUrl = null;

                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;

                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }

                    // saving the paymentID in the key guid
                    HttpContext.Session.SetString(guid, createdPayment.id);

                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment

                    var guid = HttpContext.Request.Query["guid"];
                    var email = "";
                    var password = "";
                    var executedPayment = ExecutePayment(apiContext, payerId, HttpContext.Session.GetString(guid));

                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() == "approved")
                    {
                        var body = HttpContext.Session.GetString("signupDto");
                        UserSignupDto userDto = JsonConvert.DeserializeObject<UserSignupDto>(body);
                        email =userDto.Email;
                        password=userDto.Password;
                        SResponse resp = Fetch.GotoService("api", "UserManagement/Register", "POST", body);
                        if (resp.Status && (!string.IsNullOrEmpty(resp.Resp)))
                        {
                            
                            return RedirectToAction("Login", "Account", new { area = "Security" });
                        }
                        else
                        {
                            return RedirectToAction("BillingMethod");
                        }
                    }
                    else
                        return RedirectToAction("BillingMethod");
                }
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        
        [HttpGet]
        public IActionResult ReSubscribeWithPaypal(int Id)
        {
            try
            {
                //getting the apiContext
                APIContext apiContext = PaypalConfiguration.GetAPIContext();
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = HttpContext.Request.Query["PayerID"];

                if (string.IsNullOrEmpty(payerId))
                {
                    SResponse resp = Fetch.GotoService("api", $"PricePlan/GetPricePlanById?Id={Id}", "GET");
                    if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
                    {
                        PricePlan pricePlan = JsonConvert.DeserializeObject<PricePlan>(resp.Resp);
                        HttpContext.Session.SetString("pricePlan", JsonConvert.SerializeObject(pricePlan));
                    }
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class

                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = $"{Request.Scheme}://{Request.Host.Value}" +
                                "/cms/Public/Subscription/ReSubscribeWithPaypal?";

                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution

                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment
                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = CreatePayment(apiContext, baseURI + "guid=" + guid);

                    //get links returned from paypal in response to Create function call

                    var links = createdPayment.links.GetEnumerator();

                    string paypalRedirectUrl = null;

                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;

                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }

                    // saving the paymentID in the key guid
                    HttpContext.Session.SetString(guid, createdPayment.id);

Areas/Public/Views/Subscription/Index.cshtml
@model List<AbsolCase.Models.PackageService>

@{
    ViewBag.Title = "Price Plans";
    Layout = "~/Views/Shared/_OuterLayout.cshtml";
}

@if (TempData["response"] != null)
{
    <div class="alert-danger" id="msgalert">
        @TempData["response"].ToString()
    </div>
}
<style>

    .card .card-body {
        padding: 1.5rem 1.5rem;
    }

    .card-body {
        flex: 1 1 auto;
        padding: 1rem 1rem;
    }

    .card .card-title {
        color: #010101;
        margin-bottom: 1.2rem;
        text-transform: capitalize;
        font-size: 1.125rem;
        font-weight: 600;
    }

    .text-muted, .preview-list .preview-item .preview-item-content p .content-category, .email-wrapper .mail-sidebar .menu-bar .profile-list-item a .user .u-designation, .email-wrapper .mail-list-container .mail-list .content .message_text, .email-wrapper .mail-list-container .mail-list .details .date {
        color: #737F8B !important;
    }

    .text-uppercase {
        text-transform: uppercase !important;
    }

    .text-center {
        text-align: center !important;
    }

    .card-title {
        margin-bottom: 0.5rem;
    }

    .text-center {
        text-align: center !important;
    }

    .card {
        z-index: 0;
        border: none;
        position: relative;
    }

    .card {
        box-shadow: 0 0 0 0 rgb(90 113 208 / 11%), 0 4px 16px 0 rgb(167 175 183 / 33%);
        -webkit-box-shadow: 0 0 0 0 rgb(90 113 208 / 11%), 0 4px 16px 0 rgb(167 175 183 / 33%);
        -moz-box-shadow: 0 0 0 0 rgba(90, 113, 208, 0.11), 0 4px 16px 0 rgba(167, 175, 183, 0.33);
        -ms-box-shadow: 0 0 0 0 rgba(90, 113, 208, 0.11), 0 4px 16px 0 rgba(167, 175, 183, 0.33);
        transition: background 0.25s ease;
        -webkit-transition: background 0.25s ease;
        -moz-transition: background 0.25s ease;
        -ms-transition: background 0.25s ease;
        border: none;
        border: none;
    }

    .mb-lg-0 {
        margin-bottom: 0 !important;
    }

    .mb-5 {
        margin-bottom: 3rem !important;
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid #e3e3e3;
        border-radius: 20px;
    }
</style>
<section class="pricing py-5" style="margin-top:20%">
    <div class="container">
        <div class="row">
            <!-- Free Tier -->
            @if (Model != null && Model.Count > 0)
            {
                @foreach (var plan in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-5 mb-lg-0" style="width:90%; height:400px;">
                            <div class="card-body cc">
                                <h5 class="card-title text-muted text-uppercase text-center">@plan.pricePlan.PlanName</h5>
                                <h6 class="card-price text-center">@plan.pricePlan.PriceRange<span class="period">/@plan.pricePlan.TimeRange</span></h6>
                                <hr>
                                <ul class="fa-ul">
                                    @if (plan.services != null && plan.services.Count > 0)
                                    {
                                        @foreach (var service in plan.services)
                                        {
                                            <li><span class="fa-li"><i class="fas fa-check"></i></span>@service.Name</li>
                                        }
                                    }
                                </ul>
                            </div>
                            <a href="@Url.Action("BillingMethod", "Subscription" , new { Id=plan.pricePlan.PlanID, area = "Public" }, null)" class="theme-btn-s3" style="color: black; margin-bottom: 0%; text-align:center; position:relative;width:200px; margin-left:60px;">Subscribe</a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
<script>
    setTimeout(function () {
        $("#msgalert").hide();
    }, 3500);
</script>

Areas/Public/Views/Subscription/PaymentWithBank.cshtml
@model AbsolCase.Models.PricePlan
@{
    ViewBag.Title = "Verify";
    Layout = null;
}

<link href="~/css/bootstrap.css" rel="stylesheet" />
@if (TempData["response"] != null)
{
    <div class="alert-danger" id="msgalert">
        @TempData["response"].ToString()
    </div>
};
@if (ViewBag.Payment != null && ViewBag.Payment == "success")
{
    <h4 style="text-align:center;color:brown;">Thank you for uploading the screen shot of your bank transaction, We will review your screen shot and will inform you through given email</h4>
}
else
{
    <h4 style="text-align:center;color:brown;">Thank you for choosing CMS, Please Pay $@ViewBag.Price for joining CMS, and upload the screen shot of your bank transaction</h4>
    <div class="col-md-4 col-sm-12 " style="border-style:solid;border-color:lightgray;height:280px;margin-left:30%;">
        <form method="post" enctype="multipart/form-data" action="PaymentWithBank">
            <div class="summary">
                <h3 class="headerFont forecolorpurple ng-isolate-scope" portal-translate="true"><b>From Bank</b></h3>
                <strong>Account No:  IBAN PK00 6546 89327632</strong>
                <div class="row" style="margin-left: 0px !important">

                    <label>Upload Screen Shot of Online Transaction</label>

                    <input type="file" class="form-control" id="file" name="file" accept="image/*" value="UploadScreenSHot" style="width:96%;" />
                </div>
                <div class="row mt-2" style="margin-left: 0px !important">
                    <div class="form-group">
                        <input class="btn btn-primary" value="Upload Online Invoice" type="submit" id="submit-button" style="cursor:pointer; margin-top:20px;" />
                    </div>
                </div>
            </div>
        </form>
    </div>
}
@section scripts{
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/vendors/chart.js/Chart.min.js"></script>
    <script src="~/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function () {
            $('input:file').change(
                function () {
                    if ($(this).val()) {
                        $("#submit-button").attr('disabled', false);
                    }
                });
        });
        var model = new FormData();
        var selectedFile = $("#file");
    </script>

}

Areas/Public/Views/Subscription/ReSubscribe.cshtml
@model List<AbsolCase.Models.PackageService>

@{
    ViewBag.Title = "Price Plans";
    Layout = "~/Views/Shared/_OuterLayout.cshtml";
}

@if (TempData["response"] != null)
{
    <div class="alert-danger" id="msgalert">
        @TempData["response"].ToString()
    </div>
}
<style>

    .card .card-body {
        padding: 1.5rem 1.5rem;
    }

    .card-body {
        flex: 1 1 auto;
        padding: 1rem 1rem;
    }

    .card .card-title {
        color: #010101;
        margin-bottom: 1.2rem;
        text-transform: capitalize;
        font-size: 1.125rem;
        font-weight: 600;
    }

    .text-muted, .preview-list .preview-item .preview-item-content p .content-category, .email-wrapper .mail-sidebar .menu-bar .profile-list-item a .user .u-designation, .email-wrapper .mail-list-container .mail-list .content .message_text, .email-wrapper .mail-list-container .mail-list .details .date {
        color: #737F8B !important;
    }

    .text-uppercase {
        text-transform: uppercase !important;
    }

    .text-center {
        text-align: center !important;
    }

    .card-title {
        margin-bottom: 0.5rem;
    }

    .text-center {
        text-align: center !important;
    }

    .card {
        z-index: 0;
        border: none;
        position: relative;
    }

    .card {
        box-shadow: 0 0 0 0 rgb(90 113 208 / 11%), 0 4px 16px 0 rgb(167 175 183 / 33%);
        -webkit-box-shadow: 0 0 0 0 rgb(90 113 208 / 11%), 0 4px 16px 0 rgb(167 175 183 / 33%);
        -moz-box-shadow: 0 0 0 0 rgba(90, 113, 208, 0.11), 0 4px 16px 0 rgba(167, 175, 183, 0.33);
        -ms-box-shadow: 0 0 0 0 rgba(90, 113, 208, 0.11), 0 4px 16px 0 rgba(167, 175, 183, 0.33);
        transition: background 0.25s ease;
        -webkit-transition: background 0.25s ease;
        -moz-transition: background 0.25s ease;
        -ms-transition: background 0.25s ease;
        border: none;
        border: none;
    }

    .mb-lg-0 {
        margin-bottom: 0 !important;
    }

    .mb-5 {
        margin-bottom: 3rem !important;
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid #e3e3e3;
        border-radius: 20px;
    }
</style>
<section class="pricing py-5" style="margin-top:20%">
    <div class="container">
        <div class="row">
            <!-- Free Tier -->
            @if (Model != null && Model.Count > 0)
            {
                @foreach (var plan in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-5 mb-lg-0" style="width:90%; height:400px;">
                            <div class="card-body cc">
                                <h5 class="card-title text-muted text-uppercase text-center">@plan.pricePlan.PlanName</h5>
                                <h6 class="card-price text-center">@plan.pricePlan.PriceRange<span class="period">/@plan.pricePlan.TimeRange</span></h6>
                                <hr>
                                <ul class="fa-ul">
                                    @if (plan.services != null && plan.services.Count > 0)
                                    {
                                        @foreach (var service in plan.services)
                                        {
                                            <li><span class="fa-li"><i class="fas fa-check"></i></span>@service.Name</li>
                                        }
                                    }
                                </ul>
                            </div>
                            <a href="@Url.Action("ReSubscribeWithPaypal", "Subscription" , new { Id=plan.pricePlan.PlanID, area = "Public" }, null)" class="theme-btn-s3" style="color: black; margin-bottom: 0%; text-align:center; position:relative;width:200px; margin-left:60px;">Subscribe</a>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
<script>
    setTimeout(function () {
        $("#msgalert").hide();
    }, 3500);
</script>