Areas/Lead/Controllers/LeadController.cs
using AbsolCase.Configurations;
using AbsolCase.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static AbsolCase.Configuration.RequestSender;

namespace AbsolCase.Areas.Lead.Controllers
{
    [ServiceFilter(typeof(ConfigureSession))]
    public class LeadController : Controller
    {
        public IActionResult AddPotentialClient()
        {
            string userId = string.Empty;
            string userdto = HttpContext.Session.GetString("userData");
            if (!string.IsNullOrEmpty(userdto))
            {
                UserDto userData = JsonConvert.DeserializeObject<UserDto>(userdto);
                userId = userData.Id;
            }
            SResponse resp = Fetch.GotoService("api", $"Firm/GetFirmByUserId?userId={userId}", "GET");
            if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
            {
                return View();
            }
            else
            {
                TempData["response"] = "Please Add Firm Details First";
                return RedirectToAction("AddFirm", "Firm", new { area = "Attorney" });
            }
            return View();
        }
        public IActionResult UpdateLead(int Id)
        {
            try
            {
                SResponse resp = Fetch.GotoService("api", $"Lead/GetLeadById?Id={Id}", "GET");
                if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
                {
                    LeadDetail lead = JsonConvert.DeserializeObject<LeadDetail>(resp.Resp);
                    return View(lead);
                }
                else
                    return View();
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        [HttpPost]
        public IActionResult UpdateLead(LeadDetail lead)
        {
            try
            {
                var body = JsonConvert.SerializeObject(lead);
                SResponse resp = Fetch.GotoService("api", "Lead/UpdateLead", "POST", body);
                if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
                {
                    return RedirectToAction("ManageLead");
                }
                else
                {
                    TempData["response"] = resp.Resp;
                    return View();
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
        public IActionResult ManageLead()
        {
            SResponse resplead = Fetch.GotoService("api", "Lead/GetLeads", "GET");
            if (resplead.Status && (resplead.Resp != null) && (resplead.Resp != ""))
            {
                List<LeadDetail> lead = JsonConvert.DeserializeObject<List<LeadDetail>>(resplead.Resp);
                return View(lead);
            }
            else
            {
                if (resplead.Resp == "Please Add Firm Details First")
                {
                    return RedirectToAction("AddFirm", "Firm", new { area = "Attorney" });
                }
            }
            return View();
        }
        public IActionResult BoardLead()
        {
            SResponse resplead = Fetch.GotoService("api", "Lead/GetLeads", "GET");
            if (resplead.Status && (resplead.Resp != null) && (resplead.Resp != ""))
            {
                List<LeadDetail> lead = JsonConvert.DeserializeObject<List<LeadDetail>>(resplead.Resp);
                return View(lead);
            }
            else
            {
                if (resplead.Resp == "Please Add Firm Details First")
                {
                    return RedirectToAction("AddFirm", "Firm", new { area = "Attorney" });
                }
            }
            return View();
        }
        public IActionResult DeleteLead(int Id)
        {
            try
            {
                SResponse resp = Fetch.GotoService("api", $"Lead/DeleteLead?Id={Id}", "DELETE");
                if (resp.Status && (resp.Resp != null) && (resp.Resp != ""))
                {
                    return RedirectToAction("ManageLead");
                }
                return RedirectToAction("ManageLead");
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

Areas/Lead/Views/Lead/ManageLead.cshtml
@model List<AbsolCase.Models.LeadDetail>

@{
    ViewBag.Title = "Manage Lead";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/css/Packages.css" rel="stylesheet" type="text/css" />
@if (TempData["response"] != null)
{
    <div class="alert-danger" id="msgalert">
        @TempData["response"].ToString()
    </div>
}
<div class="col-lg-12 grid-margin stretch-card">
    <input type="hidden" id="leadid" />
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Manage Lead</h4>
            <p class="card-description">
                Manage Your Lead
            </p>
            <div class="table-responsive">
                <table id="datatable" class="table table-striped  dt-responsive nowrap" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>LastName</th>
                            <th>Email</th>
                            <th>Lead Detail</th>
                            <th>Potential Case Description</th>
                            <th>Conflict Check Notes</th>
                            <th>
                                Action
                            </th>


                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Count > 0)
                        {
                            @foreach (var lead in Model)
                            {
                                <tr>
                                    <td>@lead.FirstName</td>
                                    <td>
                                        @lead.LastName
                                    </td>
                                    <td>@lead.Email</td>
                                    <td>@lead.LeadDetails</td>
                                    <td>@lead.PotentailCaseDescription</td>
                                    <td>@lead.ConflictCheckNotes</td>
                                    <td>
                                        @Html.ActionLink("Edit", "UpdateLead", "Lead", new { Id = @lead.Id }) |
                                        <a href="#" onclick="openpopup(@lead.Id, 'Are you sure to delete lead?', 'deletelead(@lead.Id)')">Delete</a> 
                                        @*<a href="#">View Details</a>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        var remoteServerURl = "";
        var token = "";
        $(function () {
            getRemoteServerURl();
            token = localStorage.getItem('token');
        });

        function getRemoteServerURl() {
            //$.ajax({
            //    type: 'GET',
            //    url: '/common/getConfigurationValue',
            //    data: { sectionName: "app", paramName: "remoteServerUrl" }
            //}).done(function (response) {
            //    remoteServerURl = response.parameter;
            //})

            var ReceivedURL = GetURL();
            remoteServerURl = ReceivedURL;
        }
        function deletelead(Id) {
                token = localStorage.getItem('token');
            $.ajax({
                type: 'Delete',
                url: `${remoteServerURl}api/Lead/DeleteLead?Id=` + Id,
                headers: { "Authorization": 'Bearer ' + token },
            }).done(function (data) {
                closepopup();
                toastr.success("lead deleted successfully");
                setTimeout(function () {
                    window.location.href = '@Url.Action("ManageLead", "Lead")'
                }, 1000);
            })
        }
        $(document).ready(function () {
            $('#datatable').dataTable({
                "columnDefs": [
                    { "searchable": false, "targets": 6 }
                ]
            });
        });
    </script>
}